auctions/urls.py
from django.urls import path

from . import views

app_name = "au"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("closedListings", views.closedListings, name="closedListings"),
    path("create", views.create_listing_view, name="create_listing_view"),
    path("auction/<int:id>", views.auction, name="auction"),
    path("auction/<int:auction_id>/addToWatchlist", views.addToWatchlist, name="addToWatchlist"),
    path("auction/<int:auction_id>/closeAuction", views.closeAuction, name="closeAuction"),
    path("auction/<int:auction_id>/bid", views.bid, name="bid"),
    path("auction/<int:auction_id>/comment", views.comment, name="comment"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("categories", views.categories, name="categories"),
    path("categories/<str:category_name>", views.category, name="category"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    username = models.CharField(max_length=64, unique=True)
    email = models.EmailField(max_length=64, unique=True)
    password = models.CharField(max_length=64)
    
    def __str__(self):
        return f"{self.username} : {self.email}"
    
class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

class Auction(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='auction_creator')
    name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=128, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    photo = models.URLField(max_length = 200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    isActive = models.BooleanField(default = True)
    users = models.ManyToManyField(User, blank=True, related_name="watchlist")

    def __str__(self):
        return f"{self.name} : {self.price}"

class Bid(models.Model):
    bid = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name="user_bid")
    auction = models.ForeignKey(Auction, on_delete = models.CASCADE, related_name="auction_bid")


class Comment(models.Model):
    comment = models.CharField(max_length=256)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_comment")
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="auction_comment")
    

auctions/forms.py
from django import forms
from .models import Auction, Category

class CreateListingForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all())

    class Meta:
        model = Auction
        fields = ('name', 'description', 'price', 'photo', 'category')
        
class BidForm(forms.Form):
    offer = forms.FloatField()
    
class CommentForm(forms.Form):
    comment = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4})
    )

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django import forms
from .models import Auction, User, Category, Bid, Comment
from .forms import CreateListingForm, BidForm, CommentForm
from django.db.models import Max


def index(request):
    auctions = Auction.objects.filter(isActive =True)
    return render(request, "auctions/index.html", {"auctions":auctions, "title":"Active Listings"})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("au:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("au:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("au:index"))
    else:
        return render(request, "auctions/register.html")

def closedListings(request):
    auctions = Auction.objects.filter(isActive =False)
    return render(request, "auctions/index.html", {"auctions":auctions, "title":"Closed Listings"})    

@login_required
@csrf_protect
def create_listing_view(request):
    form = CreateListingForm()
    categories = Category.objects.all()

    
    if request.method == "POST":
        form = CreateListingForm(request.POST)
        if form.is_valid():
            auction = form.save(commit=False)
            auction.creator = request.user
            auction.save()
            
            bid_price = form.cleaned_data["price"]
            bid = Bid.objects.create(bid=bid_price, user=request.user, auction=auction)
            return HttpResponseRedirect(reverse("au:index"))

    return render(request, "auctions/create.html", {'form': form, 'categories': categories})

@login_required
@csrf_protect
def auction(request, id):
    commentForm = CommentForm()
    auction = Auction.objects.get(id=id)
    user = User.objects.get(pk=int(request.user.id))
    is_creator = auction.creator == user
    is_watching = auction.users.filter(pk=user.pk).exists()
    is_winner = False
    
    highest_bid = auction.auction_bid.aggregate(Max('bid'))
    max_bid = highest_bid['bid__max']
    
    if max_bid is not None:
        highest_bid_obj = Bid.objects.filter(auction=auction, bid=max_bid).first()
        if highest_bid_obj:
            highest_bid_username = highest_bid_obj.user.username
            if (not(auction.isActive) and highest_bid_username == user.username):
                is_winner = True
    
    bids = Bid.objects.filter(auction=auction)
    comments = Comment.objects.filter(auction=auction)  

    return render(request, "auctions/auction.html", 
        {
            "auction":auction, "is_watching":is_watching, "bids":bids, 
            "is_creator":is_creator, "is_winner": is_winner, "commentForm": commentForm,
            "comments":comments
    })

@login_required
@csrf_protect
def addToWatchlist(request, auction_id):
    if request.method == "POST":
        auction = Auction.objects.get(id=auction_id)
        user = User.objects.get(pk=int(request.user.id))
        is_watching = auction.users.filter(pk=user.pk).exists()
        
        if is_watching:
            auction.users.remove(user)
        else:
            auction.users.add(user)
            auction.save()
            

        return HttpResponseRedirect(reverse("au:auction", kwargs={'id':auction_id}))

@login_required
@csrf_protect
def closeAuction(request, auction_id):
    if request.method == "POST":
        auction = Auction.objects.get(id=auction_id)
        user = User.objects.get(pk=int(request.user.id))
        is_creator = auction.creator == user
        
        if is_creator:
            auction.isActive = False
            auction.save()

        return HttpResponseRedirect(reverse("au:auction", kwargs={'id':auction_id}))

@login_required
@csrf_protect
def bid(request, auction_id):
    if request.method == "POST":
        form = BidForm(request.POST)
        if form.is_valid():
            auction = Auction.objects.get(id=auction_id)
            user = User.objects.get(pk=int(request.user.id))
            new_price = float(request.POST["offer"])
            # Daha önce teklif yapılmışsa
            if auction.auction_bid.exists():
                highest_bid = auction.auction_bid.aggregate(Max('bid'))['bid__max']
                if new_price > highest_bid:
                    bid = Bid.objects.create(bid=new_price, user=user, auction=auction)
                    auction.price = new_price
                    auction.save()
                else:
                    return render(request, "auctions/error.html")
            # Daha önce teklif yapılmamışsa
            else:
                if new_price > auction.price:
                    bid = Bid.objects.create(bid=new_price, user=user, auction=auction)
                    auction.price = new_price
                    auction.save()
                else:
                    return render(request, "auctions/error.html")
        else:
            form = BidForm()
    
    return HttpResponseRedirect(reverse("au:auction", kwargs={'id': auction_id}))

@login_required
@csrf_protect
def comment(request, auction_id):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            auction = Auction.objects.get(id=auction_id)
            user = User.objects.get(pk=int(request.user.id))
            comment = request.POST["comment"]
            comment = Comment.objects.create(comment=comment, user=user, auction=auction)
            comment.save()
            
    return HttpResponseRedirect(reverse("au:auction", kwargs={'id': auction_id}))

@login_required
@csrf_protect
def watchlist(request):
    auctions = Auction.objects.all()
    
    user_auction = []
    
    for auction in auctions:
        user = User.objects.get(pk=int(request.user.id))
        is_watching = auction.users.filter(pk=user.pk).exists()
        if is_watching:
            user_auction.append(auction)
            
    return render(request, "auctions/watchlist.html", {"user_auction": user_auction})

@login_required
@csrf_protect
def categories(request):
    categories = Category.objects.all()
    return render(request, "auctions/categories.html", {"categories": categories})

@login_required
@csrf_protect
def category(request, category_name):
    category_obj = get_object_or_404(Category, name=category_name)
    category_items = Auction.objects.filter(category=category_obj)
    return render(request, "auctions/category.html", {"category_items": category_items, "category_name":category_name})

    

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}


    <div class="list-group w-50 p-2">
        <span href="#" class="list-group-item list-group-item-action active h4">
            Categories
        </span>
        {% for category in categories %}

        <a href="{% url 'au:category' category_name=category.name %}" class="list-group-item list-group-item-action p-4"> {{ category.name }}</a>

        {% endfor %}
      </div>






{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}

    <div class="list-group w-50 p-2">

        <span href="#" class="list-group-item list-group-item-action active h4 uppercase">
            {{category_name}} Auctions
        </span>

        {% for item in category_items %}
        <a href="{% url 'au:auction' id=item.id %}" class="list-group-item list-group-item-action p-4"> {{ item }}</a>
        {% empty %}
            No auctions found for this category
        {% endfor %}

      </div>

{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %} {% block body %}
<h2>Create Listing</h2>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="form-group">
    <label for="name">Auction Name:</label>
    {{ form.name }}
  </div>

  <div class="form-group">
    <label for="description">Auction Description:</label>
    {{ form.description }}
  </div>

  <div class="form-group">
    <label for="price">Starting Bid Price:</label>
    {{ form.price }}
  </div>

  <div class="form-group">
    <label for="photo">Auction Photo:</label>
    {{ form.photo }}
  </div>

  <!-- <div class="form-group">
    <label for="category">Category:</label><br />
    <select id="category" name="category">
      {% for category in categories %}
      <option value="{{ category.id }}">{{ category.name }}</option>
      {% endfor %}</select
    ><br />
  </div> -->

  <div class="form-group">
    <label for="category">Category:</label><br />
    {{ form.category }}
  </div>

  <button class="btn btn-primary" type="submit">Create</button>
</form>
{% endblock %}

auctions/templates/auctions/error.html
{% extends "auctions/layout.html" %}
{% block body %}


<div class="alert alert-danger" role="alert">
    The value of your bid must be higher than the highest bid.
  </div>

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Auctions{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    <h1 class="m-3 display-3">Auctions</h1>
    <div class="m-3">
      {% if user.is_authenticated %} Signed in as
      <strong>{{ user.username }}</strong>. {% else %} Not signed in.
      <!-- prettier-ignore -->
      {% endif %}
    </div>
    <ul class="nav nav-tabs m-3">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'au:index' %}">Active Listings</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'au:closedListings' %}">Closed Listings</a>
      </li>
      {% if user.is_authenticated %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'au:create_listing_view' %}">Create Listing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'au:categories' %}">Categories</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-info" href="{% url 'au:watchlist' %}">My Watchlist</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'au:logout' %}">Log Out</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'au:login' %}">Log In</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'au:register' %}">Register</a>
      </li>
      {% endif %}
    </ul>
    {% block body %} {% endblock %}
  </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'au:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'au:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'au:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'au:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}


    <div class="list-group w-50 p-2">
        <span href="#" class="list-group-item list-group-item-action active h4">
          Watchlist
        </span>
        {% for auction in user_auction %}

        <a href="{% url 'au:auction' id=auction.id %}" class="list-group-item list-group-item-action p-4"> {{ auction }}</a>

        {% empty %}

        <h4> Your watchlist is empty </h4>

        {% endfor %}
    </div>






{% endblock %}